name = "MyLittleModpack"
author = "Sollace, Fauli1221"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2193d6c5914ffecda5243d78840e79feaaaca9a1ef0ab633f35a41bdc519aad4"

[versions]
fabric = "0.14.25"
minecraft = "1.20.2"
