name = "MyLittleModpack"
author = "Sollace, Fauli1221"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aa5ec2844716b29d611c3d04066cd3261d7768ed90da16212ec1acc2097ed59"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
