name = "MyLittleModpack"
author = "Sollace, Fauli1221"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "779e29b100a21ecf9573c4959f610ef6dab778cd4a30c32d9e2bb3efbf5438d9"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
